# @package _global_
module:
  _target_: emg2qwerty.lightning.CNNTransformerCTCModule
  in_features: 528
  mlp_features: [384]
  
  block_channels: [24, 24]
  kernel_width: 32
  
  nhead: 8              
  num_layers: 2         
  dim_feedforward: 1024 
  dropout: 0.1          

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 4000   
  padding: [1800, 200]