# @package _global_
module:
  _target_: emg2qwerty.lightning.TCNCTCModule
  in_features: 528
  mlp_features: [384]
  
  num_channels: [512, 512, 512, 512]  
  kernel_size: 5
  dropout: 0.25
  causal: false   

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]